const baseUrl="https://app.datamaxs.com"
export const signup=`${baseUrl}/category/authentication/registration/signup`
export const loginurl=`${baseUrl}/category/authentication/registration/login`
export const producturl=`${baseUrl}/category/product/`
export const buydataurl=`${baseUrl}/purchase/product/center/`
export const bankpreview=`${baseUrl}/category/preview/banks/auto`
export const userdetails=`${baseUrl}/category/preview/dashboard`
export const transactions=`${baseUrl}/query/transaction/tables/`
export const manualfunding=`${baseUrl}/category/preview/banks/manual`
export const cabletvapi=`${baseUrl}/name/checker/service/cable`
export const updatedetails=`${baseUrl}/category/preview/update/`
export const updatepass=`${baseUrl}/category/change/pass/password`
export const updatepin=`${baseUrl}/category/change/pass/pin`
export const chatbot=`${baseUrl}/communication/chatbot`
export const Apikeygermini='AIzaSyDkAdHyEkstr8HSZAlmnOCHfe1qFumQqZs'