export const mydata={
    "beneficiarys": [], 
    "category": [
    {"categoryId": 1, "categorys": [Array], 
    "networkText": "MTN"}, 
    {"categoryId": 2, "categorys": [Array], 
    "networkText": "GLO"}, 
    {"categoryId": 3, "categorys": [Array], 
    "networkText": "AIRTEL"}, 
    {"categoryId": 4, "categorys": [Array], 
    "networkText": "MOBILE"}], 
    "network": [{"chainText": "MTN-DATA", "networkId": 1, "networkText": "MTN"}, 
    {"chainText": "GLO-DATA", "networkId": 2, "networkText": "GLO"}, 
    {"chainText": "AIRTEL-DATA", "networkId": 3, "networkText": "AIRTEL"}, 
    {"chainText": "MOBILE-DATA", "networkId": 4, "networkText": "MOBILE"}], 
    "plans": [{"amount": "2000", "categoryId": 19, "categoryText": "MTN SME", "counter": 500, "productId": 10}, 
    {"amount": "2000", "categoryId": 19, "categoryText": "MTN SME", "counter": 1, "productId": 11}, 
    {"amount": "2000", "categoryId": 19, "categoryText": "MTN SME", "counter": 2, "productId": 12}, 
    {"amount": "2000", "categoryId": 19, "categoryText": "MTN SME", "counter": 3, "productId": 13}, 
    {"amount": "2000", "categoryId": 19, "categoryText": "MTN SME", "counter": 5, "productId": 14}, 
    {"amount": "2000", "categoryId": 19, "categoryText": "MTN SME", "counter": 10, "productId": 15}, 
    {"amount": "2000", "categoryId": 13, "categoryText": "GLO SME", "counter": 500, "productId": 21}, 
    {"amount": "2000", "categoryId": 13, "categoryText": "GLO SME", "counter": 1, "productId": 22}, 
    {"amount": "2000", "categoryId": 12, "categoryText": "MTN SME 2", "counter": 500, "productId": 31}, 
    {"amount": "2000", "categoryId": 12, "categoryText": "MTN SME 2", "counter": 1, "productId": 32}, 
    {"amount": "2000", "categoryId": 12, "categoryText": "MTN SME 2", "counter": 1, "productId": 33}, 
    {"amount": "2000", "categoryId": 12, "categoryText": "MTN SME 2", "counter": 2, "productId": 34}, 
    {"amount": "2000", "categoryId": 12, "categoryText": "MTN SME 2", "counter": 30, "productId": 35}, 
    {"amount": "2000", "categoryId": 12, "categoryText": "MTN SME 2", "counter": 5, "productId": 36}, 
    {"amount": "2000", "categoryId": 12, "categoryText": "MTN SME 2", "counter": 10, "productId": 36}, 
    {"amount": "2000", "categoryId": 15, "categoryText": "MTN GIFTING", "counter": 500, "productId": 41}, 
    {"amount": "2000", "categoryId": 15, "categoryText": "MTN GIFTING", "counter": 1, "productId": 42}, 
    {"amount": "2000", "categoryId": 15, "categoryText": "MTN GIFTING", "counter": 2, "productId": 43}, 
    {"amount": "2000", "categoryId": 15, "categoryText": "MTN GIFTING", "counter": 3, "productId": 44}, 
    {"amount": "2000", "categoryId": 15, "categoryText": "MTN GIFTING", "counter": 5, "productId": 45}, 
    {"amount": "2000", "categoryId": 15, "categoryText": "MTN GIFTING", "counter": 10, "productId": 46}, 
    {"amount": "2000", "categoryId": 14, "categoryText": "MTN COUPON", "counter": 1, "productId": 52}, 
    {"amount": "2000", "categoryId": 18, "categoryText": "AIRTEL COOPERATE GIFTING", "counter": 500, "productId": 71}, 
    {"amount": "2000", "categoryId": 18, "categoryText": "AIRTEL COOPERATE GIFTING", "counter": 1, "productId": 72}, 
    {"amount": "2000", "categoryId": 18, "categoryText": "AIRTEL COOPERATE GIFTING", "counter": 2, "productId": 73}, 
    {"amount": "2000", "categoryId": 18, "categoryText": "AIRTEL COOPERATE GIFTING", "counter": 3, "productId": 74}, 
    {"amount": "2000", "categoryId": 18, "categoryText": "AIRTEL COOPERATE GIFTING", 
    "counter": 5, "productId": 75}, 
    {"amount": "2000", "categoryId": 18, "categoryText": "AIRTEL COOPERATE GIFTING", "counter": 10, "productId": 76}], 
    "status": 200, "userInfo": {"bonus": 100, "username": "yomzeew", "wallet": 100}}